artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  #source_URL: https://github.com/entbappy/Branching-tutorial/raw/master/summarizer-data.zip
  source_URL: https://github.com/sadam-hussain-s/DataSets/raw/main/summarizer-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion